CL\Chill\AppointmentBundle\Entity\Appointment:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        agent:
            type: string
            length: 255
        date:
            type: datetime
        durationTime:
            type: time
        remark:
            type: text
            nullable: true
        attendee:
            type: boolean
    manyToOne:
        reason:
            targetEntity: Reason
            nullable: false
        person:
            targetEntity: CL\Chill\PersonBundle\Entity\Person
    lifecycleCallbacks: {  }
