#Reason Category
CLChillAppointmentBundle_reasoncategory:
        resource: "@CLChillAppointmentBundle/Resources/config/routing/reasoncategory.yml"
        prefix:   /reasoncategory/

#Reason
CLChillAppointmentBundle_reason:
        resource: "@CLChillAppointmentBundle/Resources/config/routing/reason.yml"
        prefix:   /reason/

#Appointment
CLChillAppointmentBundle_appointment:
        resource: "@CLChillAppointmentBundle/Resources/config/routing/appointment.yml"
        prefix:   /