reason:
    pattern: /
    defaults: {_controller: CLChillAppointmentBundle:Reason:index }

reason_new:
    pattern:  /new
    defaults: { _controller: "CLChillAppointmentBundle:Reason:new" }

reason_create:
    pattern: /create
    defaults: {_controller: CLChillAppointmentBundle:Reason:create }

reason_update:
    pattern: /update/{id}
    defaults: {_controller: CLChillAppointmentBundle:Reason:update }

reason_delete:
    pattern: /delete/{id}
    defaults: {_controller: CLChillAppointmentBundle:Reason:delete }

reason_edit:
    pattern: /edit/{id}
    defaults: {_controller: CLChillAppointmentBundle:Reason:edit }

reason_show:
    pattern: /{id}
    defaults: {_controller: CLChillAppointmentBundle:Reason:show }